// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxfIexXodXEFxXWL1n09XAr5BUs6JjTYk',
    appId: '1:800250400212:web:c9a9e72947cbe387a61a41',
    messagingSenderId: '800250400212',
    projectId: 'aqrocashato',
    authDomain: 'aqrocashato.firebaseapp.com',
    storageBucket: 'aqrocashato.firebasestorage.app',
    measurementId: 'G-1XXTYRZGFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACtb2hFwPCRZ48UTh10cqrnqp2C3tdi6o',
    appId: '1:800250400212:android:290f06063bcd9e70a61a41',
    messagingSenderId: '800250400212',
    projectId: 'aqrocashato',
    storageBucket: 'aqrocashato.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGaT9mOvF1AfC4nlP9Rk3xuna43nZxOgE',
    appId: '1:800250400212:ios:9ae41a4f14f9f4b1a61a41',
    messagingSenderId: '800250400212',
    projectId: 'aqrocashato',
    storageBucket: 'aqrocashato.firebasestorage.app',
    iosBundleId: 'in.no1ads.timewallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxfIexXodXEFxXWL1n09XAr5BUs6JjTYk',
    appId: '1:800250400212:web:1d634511587d482ca61a41',
    messagingSenderId: '800250400212',
    projectId: 'aqrocashato',
    authDomain: 'aqrocashato.firebaseapp.com',
    storageBucket: 'aqrocashato.firebasestorage.app',
    measurementId: 'G-6D58G97LXP',
  );
}
